### ISSUE TITLE
How to convert labels to KITTI in JRDB2022

### ISSUE THREAD

**Issue by xifen523** [jinzhengguang/RPEA#1]
Thank you for your very good work.

I am currently working with the JRDB2022 dataset and am interested in converting the dataset annotations to KITTI format for compatibility with my pedestrian detection models. I noticed that for JRDB2019, the script `./RPEA/lib/jrdb_devkit/detection_eval/convert_labels_to_KITTI.py` is typically used for this conversion.

However, I am unsure if this script is directly applicable to the JRDB2022 dataset due to possible differences in dataset structure or annotation specifics between the 2019 and 2022 versions. Could you provide guidance on whether the existing script can be used for JRDB2022, or if there is an updated method or script available for this conversion?

Any help or pointers would be greatly appreciated as it would significantly aid in aligning the JRDB2022 data with my project requirements.

Thank you!

**Comment by jinzhengguang** [comment]
Yes, the script `convert_labels_to_KITTI.py` is also applicable to the JRDB2022 dataset.
