### ISSUE TITLE
How to evaluate your model

### ISSUE THREAD

**Issue by malaz24** [jinzhengguang/RPEA#2]
Thanks for the interesting work.
I want to ask how to evaluate the predictions (AP). Should I use the python script in lib/jrdb_det3d_eval/example.py or the c++ script in lib/jrdb_devkit/detection_eval/evaluate_object.cpp?

**Comment by jinzhengguang** [comment]
> Thanks for the interesting work. I want to ask how to evaluate the predictions (AP). Should I use the python script in lib/jrdb_det3d_eval/example.py or the c++ script in lib/jrdb_devkit/detection_eval/evaluate_object.cpp?

It is officially recommended to use the command `evaluate_object.cpp`.

**Comment by malaz24** [comment]
Thank you! Could you please share your output_file.txt when you use the cpp file on val set?

**Comment by malaz24** [comment]
Also, how can did you calculate the AP (0.3,0.5,0.7) from this txt file?

**Comment by jinzhengguang** [comment]
> Also, how can did you calculate the AP (0.3,0.5,0.7) from this txt file?

Please visit [the official benchmark evaluation website](https://jrdb.erc.monash.edu/benchmark/) and follow their guidelines for uploading and evaluating your results. The site includes instructions for formatting your .txt file and calculating AP metrics according to their standardized process.

**Comment by jinzhengguang** [comment]
> Thank you! Could you please share your output_file.txt when you use the cpp file on val set?

To generate the `output_file.txt` results on the validation set using the provided command, you can run:

```bash
python train.py --cfg ./jrdb19.yaml --evaluation --ckpt RPEA_JRDB2019.pth
```

This command will produce the `output_file.txt` file as output, containing the evaluation results on the validation set, based on the configurations specified in `jrdb19.yaml` and the checkpoint `RPEA_JRDB2019.pth`.

**Comment by malaz24** [comment]
> > Thank you! Could you please share your output_file.txt when you use the cpp file on val set?
> 
> To generate the `output_file.txt` results on the validation set using the provided command, you can run:
> 
> ```shell
> python train.py --cfg ./jrdb19.yaml --evaluation --ckpt RPEA_JRDB2019.pth
> ```
> 
> This command will produce the `output_file.txt` file as output, containing the evaluation results on the validation set, based on the configurations specified in `jrdb19.yaml` and the checkpoint `RPEA_JRDB2019.pth`.

No I meant if I have this output_file.txt which I get after evaluating on the val set (which we have its labels), how can I get the AP (0.3,0.5,0.7) from this txt file, similar to the leaderboard?
