### ISSUE TITLE
WHEN DO EVAL ON YOUR WEIGHTS

### ISSUE THREAD

**Issue by syd-21** [jinzhengguang/RPEA#4]
python train.py --cfg ./jrdb19.yaml --evaluation --ckpt JRDB2019.pth
/media/bvb/SSD-2/jrd/RPEA/lib/jrdb_det3d_eval/jrdb_det3d_eval/eval.py:13: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def get_thresholds(scores: np.ndarray, num_gt, num_sample_pts=41):
2024-11-14 16:44:19,043  DEBUG  Log directory: /media/bvb/SSD-2/jrd/RPEA/logs/unet_bl_voxel_jrdb_0.05_0.1_EVAL_20241114_164419
2024-11-14 16:44:19,047  DEBUG  Backup ./jrdb19.yaml
2024-11-14 16:44:19,048   INFO  CUDA_VISIBLE_DEVICES=ALL
2024-11-14 16:44:19,049  DEBUG  Pipeline starts.
Traceback (most recent call last):
  File "train.py", line 86, in <module>
    pipeline.load_ckpt(model, args.ckpt)
  File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/pipeline/pipeline.py", line 37, in load_ckpt
    epoch, step = self.logger.load_ckpt(ckpt, model, self.optim)
  File "/media/bvb/SSD-2/jrd/RPEA/lidar_det/pipeline/logger.py", line 199, in load_ckpt
    model.load_state_dict(ckpt["model_state"])
  File "/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MinkUNetDetector:
	Missing key(s) in state_dict: "stage1.0.net.0.weight", "stage1.0.net.0.bias", "stage2.0.net.0.weight", "stage2.0.net.0.bias", "stage3.0.net.0.weight", "stage3.0.net.0.bias", "stage4.0.net.0.weight", "stage4.0.net.0.bias", "up1.0.net.0.weight", "up1.0.net.0.bias", "up2.0.net.0.weight", "up2.0.net.0.bias", "up3.0.net.0.weight", "up3.0.net.0.bias", "up4.0.net.0.weight", "up4.0.net.0.bias", "pathx0.0.basicconv.net.0.weight", "pathx0.0.basicconv.net.0.bias", "pathx0.1.basicconv.net.0.weight", "pathx0.1.basicconv.net.0.bias", "pathx0.2.basicconv.net.0.weight", "pathx0.2.basicconv.net.0.bias", "pathx0.3.basicconv.net.0.weight", "pathx0.3.basicconv.net.0.bias", "pathx1.0.basicconv.net.0.weight", "pathx1.0.basicconv.net.0.bias", "pathx1.1.basicconv.net.0.weight", "pathx1.1.basicconv.net.0.bias", "pathx1.2.basicconv.net.0.weight", "pathx1.2.basicconv.net.0.bias", "pathx2.0.basicconv.net.0.weight", "pathx2.0.basicconv.net.0.bias", "pathx2.1.basicconv.net.0.weight", "pathx2.1.basicconv.net.0.bias", "pathx3.0.basicconv.net.0.weight", "pathx3.0.basicconv.net.0.bias". 
	Unexpected key(s) in state_dict: "stage1.0.net.0.kernel", "stage2.0.net.0.kernel", "stage3.0.net.0.kernel", "stage4.0.net.0.kernel", "up1.0.net.0.kernel", "up2.0.net.0.kernel", "up3.0.net.0.kernel", "up4.0.net.0.kernel", "pathx0.0.basicconv.net.0.kernel", "pathx0.1.basicconv.net.0.kernel", "pathx0.2.basicconv.net.0.kernel", "pathx0.3.basicconv.net.0.kernel", "pathx1.0.basicconv.net.0.kernel", "pathx1.1.basicconv.net.0.kernel", "pathx1.2.basicconv.net.0.kernel", "pathx2.0.basicconv.net.0.kernel", "pathx2.1.basicconv.net.0.kernel", "pathx3.0.basicconv.net.0.kernel".

**Comment by jinzhengguang** [comment]
First, download our weight file, RPEA_JRDB2019.pth, and place it in the "bin" folder. Then, run the following command:  
`python train.py --cfg ./jrdb19.yaml --evaluation --ckpt RPEA_JRDB2019.pth`

**Comment by syd-21** [comment]
@jinzhengguang 

(jrd2) bvb@bvb-09:/media/bvb/SSD-2/jrd/RPEA/bin$ python train.py --cfg ./jrdb19.yaml --evaluation --ckpt RPEA_JRDB2019.pth
Traceback (most recent call last):
  File "train.py", line 5, in <module>
    from lidar_det.dataset import get_dataloader
  File "/media/bvb/SSD-2/jrd/RPEA/bin/lidar_det/dataset/__init__.py", line 1, in <module>
    from .builder import *
  File "/media/bvb/SSD-2/jrd/RPEA/bin/lidar_det/dataset/builder.py", line 2, in <module>
    from .dataset_det3d import JRDBDet3D, NuScenesDet3D
  File "/media/bvb/SSD-2/jrd/RPEA/bin/lidar_det/dataset/dataset_det3d.py", line 6, in <module>
    from torchsparse.utils import sparse_quantize
ImportError: cannot import name 'sparse_quantize' from 'torchsparse.utils' (/home/bvb/anaconda3/envs/jrd2/lib/python3.8/site-packages/torchsparse/utils/__init__.py)

**Comment by syd-21** [comment]
File "train.py", line 80, in <module>
    model = get_model(cfg["model"])
  File "/media/bvb/SSD-2/jrd/RPEA/bin/lidar_det/model/builder.py", line 17, in get_model
    net = MinkUNetDetector(**model_cfg["kwargs"])
  File "/media/bvb/SSD-2/jrd/RPEA/bin/lidar_det/model/builder.py", line 54, in __init__
    super().__init__(cr=cr, run_up=run_up, num_classes=out_dim, input_dim=input_dim)
  File "/media/bvb/SSD-2/jrd/RPEA/bin/lidar_det/model/nets/minkunet.py", line 153, in __init__
    ResidualBlock(cs[0], cs[1], ks=3, stride=1, dilation=1),
  File "/media/bvb/SSD-2/jrd/RPEA/bin/lidar_det/model/nets/minkunet.py", line 98, in __init__
    self.catt = ChannelAttention(channel=outc)
  File "/media/bvb/SSD-2/jrd/RPEA/bin/lidar_det/model/nets/minkunet.py", line 64, in __init__
    self.spnnavg = spnn.GlobalAveragePooling()
AttributeError: module 'torchsparse.nn' has no attribute 'GlobalAveragePooling'

**Comment by syd-21** [comment]
@jinzhengguang  solved Thanks

**Comment by jinzhengguang** [comment]
> File "train.py", line 80, in model = get_model(cfg["model"]) File "/media/bvb/SSD-2/jrd/RPEA/bin/lidar_det/model/builder.py", line 17, in get_model net = MinkUNetDetector(**model_cfg["kwargs"]) File "/media/bvb/SSD-2/jrd/RPEA/bin/lidar_det/model/builder.py", line 54, in **init** super().**init**(cr=cr, run_up=run_up, num_classes=out_dim, input_dim=input_dim) File "/media/bvb/SSD-2/jrd/RPEA/bin/lidar_det/model/nets/minkunet.py", line 153, in **init** ResidualBlock(cs[0], cs[1], ks=3, stride=1, dilation=1), File "/media/bvb/SSD-2/jrd/RPEA/bin/lidar_det/model/nets/minkunet.py", line 98, in **init** self.catt = ChannelAttention(channel=outc) File "/media/bvb/SSD-2/jrd/RPEA/bin/lidar_det/model/nets/minkunet.py", line 64, in **init** self.spnnavg = spnn.GlobalAveragePooling() AttributeError: module 'torchsparse.nn' has no attribute 'GlobalAveragePooling'

`pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v1.2.0`
