### ISSUE TITLE
Can you help me how to submit results

### ISSUE THREAD

**Issue by syd-21** [jinzhengguang/RPEA#5]
I got 26 folders of test set results, which are around 4GB, but at JRDB website it says the limit is 1gb GB. Can you guide me do I have to submit all results for a few?

Thanks!

**Comment by jinzhengguang** [comment]
> I got 26 folders of test set results, which are around 4GB, but at JRDB website it says the limit is 1gb GB. Can you guide me do I have to submit all results for a few?
> 
> Thanks!

You can use the `filter_submission.py` script to reduce the size of your test set results by filtering out predictions with low confidence scores.
